### PR TITLE
Handle ruby 4

### LINKED ISSUE #340: Issue with running pg_query with ruby 4.0.0-preview2
when running `bin/rails console` on the recently release ruby preview, I got this error:

```ruby
bin/rails aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'pg_query'. (Bundler::GemRequireError)
Gem Load Error is: dlsym(0xbf7a98f0, ruby_abi_version): symbol not found - ruby_abi_version
Backtrace for gem load error is:
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/4.0.0+0/bundled_gems.rb:60:in 'Kernel.require'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/4.0.0+0/bundled_gems.rb:60:in 'block (2 levels) in Kernel#replace_require'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in 'Kernel#require'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/gems/zeitwerk-2.7.3/lib/zeitwerk/core_ext/kernel.rb:34:in 'Kernel#require'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/gems/pg_query-6.1.0/lib/pg_query.rb:7:in '<main>'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/4.0.0+0/bundled_gems.rb:60:in 'Kernel#require'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/4.0.0+0/bundled_gems.rb:60:in 'block (2 levels) in Kernel.replace_require'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/gems/zeitwerk-2.7.3/lib/zeitwerk/core_ext/kernel.rb:34:in 'Kernel.require'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/gems/bundler-2.7.2/lib/bundler/runtime.rb:63:in 'block (2 levels) in Bundler::Runtime#require'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/gems/bundler-2.7.2/lib/bundler/runtime.rb:58:in 'Array#each'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/gems/bundler-2.7.2/lib/bundler/runtime.rb:58:in 'block in Bundler::Runtime#require'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/gems/bundler-2.7.2/lib/bundler/runtime.rb:52:in 'Array#each'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/gems/bundler-2.7.2/lib/bundler/runtime.rb:52:in 'Bundler::Runtime#require'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/gems/bundler-2.7.2/lib/bundler.rb:214:in 'Bundler.require'
/Users/chedli/code/work/hoggo/config/application.rb:44:in '<main>'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/4.0.0+0/bundled_gems.rb:60:in 'Kernel.require'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/4.0.0+0/bundled_gems.rb:60:in 'block (2 levels) in Kernel#replace_require'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in 'Kernel#require'
/Users/chedli/code/work/hoggo/Rakefile:3:in '<main>'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/gems/rake-13.3.1/lib/rake/rake_module.rb:29:in 'Kernel#load'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/gems/rake-13.3.1/lib/rake/rake_module.rb:29:in 'Rake.load_rakefile'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/gems/rake-13.3.1/lib/rake/application.rb:740:in 'Rake::Application#raw_load_rakefile'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/gems/rake-13.3.1/lib/rake/application.rb:126:in 'block in Rake::Application#load_rakefile'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/gems/rake-13.3.1/lib/rake/application.rb:214:in 'Rake::Application#standard_exception_handling'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/gems/rake-13.3.1/lib/rake/application.rb:125:in 'Rake::Application#load_rakefile'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/bundler/gems/rails-6388aec724df/railties/lib/rails/commands/rake/rake_command.rb:48:in 'block in Rails::Command::RakeCommand.with_rake'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/gems/rake-13.3.1/lib/rake/rake_module.rb:59:in 'Rake.with_application'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/bundler/gems/rails-6388aec724df/railties/lib/rails/commands/rake/rake_command.rb:46:in 'Rails::Command::RakeCommand.with_rake'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/bundler/gems/rails-6388aec724df/railties/lib/rails/commands/rake/rake_command.rb:20:in 'Rails::Command::RakeCommand.perform'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/bundler/gems/rails-6388aec724df/railties/lib/rails/command.rb:150:in 'Rails::Command.invoke_rake'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/bundler/gems/rails-6388aec724df/railties/lib/rails/command.rb:67:in 'block in Rails::Command.invoke'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/bundler/gems/rails-6388aec724df/railties/lib/rails/command.rb:143:in 'Rails::Command.with_argv'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/bundler/gems/rails-6388aec724df/railties/lib/rails/command.rb:63:in 'Rails::Command.invoke'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/bundler/gems/rails-6388aec724df/railties/lib/rails/commands.rb:18:in '<main>'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/4.0.0+0/bundled_gems.rb:60:in 'Kernel.require'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/4.0.0+0/bundled_gems.rb:60:in 'block (2 levels) in Kernel#replace_require'
/Users/chedli/.rbenv/versions/4.0.0-preview2/lib/ruby/gems/4.0.0+0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in 'Kernel#require'
bin/rails:6:in '<main>'
```

### PR DESCRIPTION
**Pull request by chaadow**
Fixes #340

### CODE REVIEW

**Comment by chaadow** [comment]
I think if we stop supporting ruby 3.1 all these checks can disappear 👍🏼

File: ext/pg_query/extconf.rb [hunk 1]
```diff
@@ -29,7 +29,7 @@ def export_ruby_abi_version
   return false if m.nil?
   major = m[1].to_i
   minor = m[2].to_i
-  major >= 3 && minor >= 2
+  ((major >= 3 && minor >= 2) || major >= 4)
```
Comment (lfittl) [inline ext/pg_query/extconf.rb:32]: Ahh. Right, this makes a lot of sense.

**Review by lfittl — APPROVED** [review]

**Comment by lfittl** [comment]
@chaadow Thanks for getting this addressed! We'll probably do a release in 1-2 weeks that will include this change.

**Comment by chaadow** [comment]
hi! @lfittl is it possible to cut a release please 🙏🏼
