### PR TITLE
Deparse EXPLAIN

### LINKED ISSUE #90: deparse fails on ExplainStmt
`print PgQuery.parse("explain select 1").deparse` blows up

### PR DESCRIPTION
**Pull request by herwinw**
This fixes #90

### CODE REVIEW

File: lib/pg_query/deparse.rb [hunk 1]
```diff
@@ -1068,6 +1070,14 @@ def deparse_drop(node)
       output.join(' ')
     end
 
+    def deparse_explain(node)
+      output = ['EXPLAIN']
+      options = node.fetch('options', []).map { |option| option['DefElem']['defname'].upcase }
+      output.concat(options)
```
Comment (lfittl) [inline lib/pg_query/deparse.rb]: We should probably use the `EXPLAIN (ANALYZE, BUFFERS)` syntax here, so multiple elements work correctly

Comment (herwinw) [reply lib/pg_query/deparse.rb]: I didn't even know that was possible ;)
